[workspace]
channels = ["conda-forge", "bioconda"]
name = "nf-versions"
platforms = ["linux-64", "osx-64", "osx-arm64"]

[activation.env]
JAVA_HOME = "${PIXI_PROJECT_ROOT}/.pixi/envs/${PIXI_ENVIRONMENT_NAME}/lib/jvm"
PATH = "${PIXI_PROJECT_ROOT}/.pixi/envs/${PIXI_ENVIRONMENT_NAME}/lib/jvm/bin:$PATH"

[feature.bcftools.dependencies]
bcftools = { version = "==1.23", channel = "bioconda" }

[feature.bwa-mem2.dependencies]
bwa-mem2 = { version = "==2.2.1", channel = "bioconda" }

[feature.falco.dependencies]
falco = { version = "==1.2.5", channel = "bioconda" }

[feature.fgbio.dependencies]
fgbio = { version = "==3.1.2", channel = "bioconda" }

[feature.picard.dependencies]
picard = { version = "==3.4.0", channel = "bioconda" }

[feature.samtools.dependencies]
samtools = { version = "==1.23", channel = "bioconda" }

[feature.splitcode.dependencies]
splitcode = { version = "==0.31.6", channel = "bioconda" }

[environments]
bcftools = { features = ["bcftools"] }
bwa-mem2 = { features = ["bwa-mem2"] }
falco = { features = ["falco"] }
fgbio = { features = ["fgbio"] }
picard = { features = ["picard"] }
samtools = { features = ["samtools"] }
splitcode = { features = ["splitcode"] }
