name: CI

on: [push]

jobs:
  test:
    name: Build and Test the Plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        JAVA_VERSION: [17, 21]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          submodules: 'true'

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520  # v5.4.0
        with:
          java-version: ${{ matrix.JAVA_VERSION}}
          architecture: x64
          distribution: adopt

      - name: Compile
        run: |
          make clean
          make assemble

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0

      - name: Install all Pixi environments (for full test suite)
        run: pixi install --all

      - name: Install
        run: make install

      - name: Test
        run: make test
        env:
          GRADLE_OPTS: '-Dorg.gradle.daemon=false'
